substitutions:

  # Identifiers
  device_id: <YOUR_DEVICE_ID>
  entity_id: <YOUR_ENTITY_ID>
  device_name: <YOUR_DEVICE_NAME>
  dehumidifier_entity_name: <YOUR_DEHUMIDIFIER_ENTITY_NAME>
  manufacturer: <YOUR_MANUFACTURER>
  model: <YOUR_MODEL>

  # GPIOs
  heat_pump_relay: <GPIO>   # relay to turn heat pump on/off
  fan_speed_relay: <GPIO>   # SPDT relay for fan speed control (high/low)
  fan_relay: <GPIO>         # relay to turn fan on/off
  tank_full_sensor: <GPIO>  # tank full sensor
  i2c_sda: <GPIO>           # humidity sensor SDA
  i2c_scl: <GPIO>           # humidity sensor SCL
  

packages:
  - !include packages/mqtt/discovery.yaml
  - !include packages/mqtt/publish_state.yaml
  - !include packages/config.yaml
  - !include packages/humidity.yaml
  - !include packages/logic.yaml
  - !include packages/heat_pump.yaml
  - !include packages/fan.yaml