substitutions:

  # Identifiers
  device_id: "PB-D-23-EU"
  entity_id: "pb_d_23_eu"
  device_name: "Dehumidifier"
  dehumidifier_entity_name: "Dehumidifier"
  manufacturer: "ProBreeze"
  model: "PB-D-23-EU"

  # GPIOs
  heat_pump_relay: GPIO32   # relay to turn heat pump on/off
  fan_speed_relay: GPIO25   # SPDT relay for fan speed control (high/low)
  fan_relay: GPIO33         # relay to turn fan on/off
  tank_full_sensor: GPIO26  # tank full sensor
  i2c_sda: GPIO21           # humidity sensor SDA
  i2c_scl: GPIO22           # humidity sensor SCL
  

packages:
  - !include packages/mqtt/discovery.yaml
  - !include packages/mqtt/publish_state.yaml
  - !include packages/config.yaml
  - !include packages/humidity.yaml
  - !include packages/logic.yaml
  - !include packages/heat_pump.yaml
  - !include packages/fan.yaml