i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

sensor:
  - platform: shtcx
    update_interval: 60s
    humidity:
      name: "Internal Humidity"
      id: internal_humidity
      on_value:
        then:
          - component.update: humidity
