select:
  - platform: template
    name: "Dehumidifier Fan Speed"
    id: fan_speed
    icon: "mdi:fan-chevron-up"
    options:
      - "low"
      - "high"
    web_server:
      sorting_weight: 2
    optimistic: true
    initial_option: "high"
    restore_value: yes
    on_value:
      then:
        - switch.control:
            id: fan_high
            state: !lambda 'return x == "high";'
        - script.execute: publish_full_state


script:
  - id: fan_force
    mode: restart
    then:
      - binary_sensor.template.publish:
          id: fan_forced
          state: true
      - switch.turn_on: fan_raw
      - delay: 5min
      - binary_sensor.template.publish:
          id: fan_forced
          state: false
      - if:
          condition:
            switch.is_off: fan
          then:
            - switch.turn_off: fan_raw

binary_sensor:

  - platform: template
    id: fan_forced
    name: "Fan Forced"
    icon: "mdi:fan-alert"
    web_server:
      sorting_weight: 4
    entity_category: diagnostic

  - platform: template
    id: fan_state
    name: "Fan"
    icon: "mdi:fan"
    web_server:
      sorting_weight: 3
    entity_category: diagnostic
    lambda: |-
      if (id(fan_raw).state) {
        return true;
      } else {
        return false;
      }

switch:

  - platform: template
    id: fan
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: tank_full
          then:
            - switch.template.publish:
                id: fan
                state: ON
            - switch.turn_on: fan_raw
    turn_off_action:
      - switch.template.publish:
                id: fan
                state: OFF
      - delay: 1s # Wait for heat_pump_raw on_turn_off to trigger fan_force first
      - if:
          condition:
            binary_sensor.is_off: fan_forced
          then:
            - switch.turn_off: fan_raw


  - platform: gpio
    pin: 
      number: ${fan_speed_relay}
      inverted: true
    id: fan_high

  - platform: gpio
    pin: 
      number: ${fan_relay}
      inverted: true
    id: fan_raw