i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  scan: true
  id: bus_a

sensor:
  - platform: shtcx
    update_interval: 60s
    humidity:
      name: "Internal Humidity"
      id: internal_humidity
      icon: "mdi:water-percent"
      web_server:
        sorting_weight: 4
      on_value:
        then:
          - component.update: humidity
    temperature:
      name: "Internal Temperature"
      id: internal_temperature
      icon: "mdi:thermometer"
      web_server:
        sorting_weight: 5

  - platform: mqtt_subscribe
    id: external_humidity
    name: "External Humidity"
    icon: "mdi:water-percent"
    device_class: humidity
    unit_of_measurement: "%"
    topic: dehumidifier/external_hum
    on_value:
      then:
        - component.update: humidity
        - script.execute: external_humidity_watchdog
    web_server:
      sorting_weight: 6


  - platform: template
    id: humidity
    lambda: |-
      float external = id(external_humidity).state;
      float internal = id(internal_humidity).state;
      if (id(use_external_humidity_sensor).state && !isnan(external)) {
        return external;
      } else {
        return internal;
      }
    on_value:
      then:
        - mqtt.publish:
            topic: dehumidifier/current_hum
            payload: !lambda |-
              if (isnan(x)) return std::string("None");
              return to_string((int)roundf(x));
        - script.execute: apply_logic
        - script.execute: publish_full_state

switch:
  - platform: template
    id: use_external_humidity_sensor
    name: "Use External Sensor"
    icon: "mdi:cog"
    optimistic: true
    web_server:
      sorting_weight: 7
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - mqtt.publish:
          topic: dehumidifier/use_external_humidity_sensor_state
          payload: "ON"
      - component.update: humidity
    on_turn_off:
      - mqtt.publish:
          topic: dehumidifier/use_external_humidity_sensor_state
          payload: "OFF"
      - component.update: humidity


script:
  - id: external_humidity_watchdog
    mode: restart
    then:
      - delay: 2min
      - switch.turn_off: use_external_humidity_sensor