globals:
  - id: boot_completed
    type: bool
    initial_value: '0'


script:
  - id: defrost
    mode: restart
    then:
      - delay: 45min
      - binary_sensor.template.publish:
          id: defrosting
          state: true
      - switch.turn_off: heat_pump_raw
      - script.execute: publish_full_state
      - delay: 5min
      - binary_sensor.template.publish:
          id: defrosting
          state: false
      - if:
          condition:
            switch.is_on: heat_pump
          then:
            - switch.turn_on: heat_pump_raw
      - script.execute: publish_full_state


switch:

  - platform: template
    id: heat_pump
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: tank_full
          then:
            - switch.template.publish:
                id: heat_pump
                state: ON
            - if:
                condition:
                  binary_sensor.is_off: defrosting
                then:
                  - switch.turn_on: heat_pump_raw
    turn_off_action:
      - switch.template.publish:
                id: heat_pump
                state: OFF
      - switch.turn_off: heat_pump_raw


  - platform: gpio
    id: heat_pump_raw
    pin:
      number: ${heat_pump_relay}
      inverted: true
    on_turn_on:
      - script.execute: defrost
      - script.stop: fan_force
      - binary_sensor.template.publish:
          id: fan_forced
          state: false
    on_turn_off:
      - if:
          condition:
            lambda: 'return id(boot_completed);'
          then:
            - script.execute: fan_force
            - if:
                condition:
                  binary_sensor.is_off: defrosting
                then:
                  - script.stop: defrost

binary_sensor:

  - platform: template
    id: heat_pump_state
    name: "Heat Pump"
    icon: "mdi:heating-coil"
    entity_category: diagnostic
    web_server:
      sorting_weight: 2
    lambda: |-
      if (id(heat_pump_raw).state) {
        return true;
      } else {
        return false;
      }

  - platform: template
    id: defrosting
    name: "Defrosting"
    icon: "mdi:snowflake"
    web_server:
      sorting_weight: 7

  - platform: gpio
    id: tank_full
    name: "Tank Full"
    icon: "mdi:format-color-fill"
    web_server:
      sorting_weight: 8
    pin:
      number: ${tank_full_sensor}
      mode: INPUT_PULLUP
    on_press:
      - switch.turn_off: heat_pump
      - switch.turn_off: fan
      - script.execute: publish_full_state
    on_release:
      - script.execute: apply_logic
      - script.execute: publish_full_state