i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  scan: true
  id: bus_a

sensor:
  - platform: shtcx
    update_interval: 60s
    humidity:
      name: "Internal Humidity"
      id: internal_humidity
      on_value:
        then:
          - component.update: humidity

  - platform: mqtt_subscribe
    id: external_humidity
    name: "External Humidity"
    device_class: humidity
    unit_of_measurement: "%"
    topic: dehumidifier/external_hum


  - platform: template
    id: humidity
    lambda: |-
      if (id(use_external_humidity_sensor).state) {
        return id(external_humidity).state;
      } else {
        return id(internal_humidity).state;
      }
    on_value:
      then:
        - mqtt.publish:
            topic: dehumidifier/current_hum
            payload: !lambda 'return to_string((int)roundf(x));'
        - script.execute: apply_logic
        - script.execute: publish_full_state

switch:
  - platform: template
    id: use_external_humidity_sensor
    name: "Use External Sensor"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - mqtt.publish:
          topic: dehumidifier/use_external_humidity_sensor_state
          payload: "ON"
      - component.update: humidity
    on_turn_off:
      - mqtt.publish:
          topic: dehumidifier/use_external_humidity_sensor_state
          payload: "OFF"
      - component.update: humidity